name: Test and Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install dependencies
        run: |
          cd ui
          npm ci

      - name: Run unit tests
        run: |
          cd ui
          npm test

      - name: Run ESLint
        run: |
          cd ui
          if [ -f "package.json" ] && grep -q "lint" package.json; then
            npm run lint
          else
            npx eslint .
          fi

      - name: Build frontend
        run: |
          cd ui
          npm run build

      - name: Run e2e tests
        run: |
          cd ui
          npm run preview &
          npx wait-on http://localhost:4173
          npm run e2e
        env:
          CI: true

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ui/cypress/screenshots

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: bridge/go.sum

      - name: Build backend
        run: |
          cd bridge
          go build ./...

      - name: Run tests
        run: |
          cd bridge
          go test -v ./...

      - name: Run go vet
        run: |
          cd bridge
          go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          working-directory: bridge
          version: "2023.1.7"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          working-directory: bridge
          version: latest

      - name: Check formatting
        run: |
          cd bridge
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Go code is not formatted:"
            gofmt -s -l .
            exit 1
          fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Gosec
        run: go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest

      - name: Run Gosec Security Scanner
        run: |
          cd bridge
          $HOME/go/bin/gosec -fmt sarif -out ../gosec.sarif ./...

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec.sarif

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check npm dependencies
        run: |
          cd ui
          npm audit --audit-level=high

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check Go dependencies
        run: |
          cd bridge
          go list -json -deps ./... | jq -r 'select(.Module != null) | .Module.Path' | sort -u > deps.txt
          echo "Go dependencies:"
          cat deps.txt

  trivy-scan:
    name: Container and License Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Upload Trivy scan results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Generate Go SBOM
        run: |
          cd bridge
          go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest
          export PATH="$HOME/go/bin:$PATH"
          cyclonedx-gomod mod -output ../bom-go.json .

      - name: Generate npm SBOM
        run: |
          cd ui
          npm ci
          npx @cyclonedx/cyclonedx-npm --output ../bom-npm.json

      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            bom-go.json
            bom-npm.json
          retention-days: 7
